// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package gRpc;

/**
 * Protobuf enum {@code FilterAction}
 */
public enum FilterAction
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ASK = 0;</code>
   */
  ASK(0),
  /**
   * <code>BID = 1;</code>
   */
  BID(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ASK = 0;</code>
   */
  public static final int ASK_VALUE = 0;
  /**
   * <code>BID = 1;</code>
   */
  public static final int BID_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FilterAction valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FilterAction forNumber(int value) {
    switch (value) {
      case 0: return ASK;
      case 1: return BID;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FilterAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FilterAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FilterAction>() {
          public FilterAction findValueByNumber(int number) {
            return FilterAction.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return gRpc.StockServiceOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final FilterAction[] VALUES = values();

  public static FilterAction valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FilterAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:FilterAction)
}

