// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package gRpc;

public interface FilterQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FilterQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>uint32 quantity = 2;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>.FilterAction action = 3;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.FilterAction action = 3;</code>
   * @return The action.
   */
  gRpc.FilterAction getAction();
}
