// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package gRpc;

public interface StockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Stock)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>double price = 3;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <code>double percentageChange = 4;</code>
   * @return The percentageChange.
   */
  double getPercentageChange();

  /**
   * <code>uint64 date = 5;</code>
   * @return The date.
   */
  long getDate();
}
