// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package gRpc;

public final class StockServiceOuterClass {
  private StockServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FilterQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FilterQuery_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradesDate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradesDate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeLogMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeLogMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Stock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Stock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022StockService.proto\"N\n\013FilterQuery\022\016\n\006s" +
      "ymbol\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\r\022\035\n\006action\030" +
      "\003 \001(\0162\r.FilterAction\"\032\n\nTradesDate\022\014\n\004da" +
      "te\030\001 \001(\t\"\036\n\017TradeLogMessage\022\013\n\003log\030\001 \001(\t" +
      "\"]\n\005Order\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price\030\002 \001(\001" +
      "\022\020\n\010quantity\030\003 \001(\r\022\027\n\006action\030\004 \001(\0162\007.Act" +
      "ion\022\n\n\002id\030\005 \001(\t\"7\n\006Status\022\027\n\017responseMes" +
      "sage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\"\\\n\005Stoc" +
      "k\022\016\n\006symbol\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005price" +
      "\030\003 \001(\001\022\030\n\020percentageChange\030\004 \001(\001\022\014\n\004date" +
      "\030\005 \001(\004\"\007\n\005Empty* \n\014FilterAction\022\007\n\003ASK\020\000" +
      "\022\007\n\003BID\020\001*\033\n\006Action\022\007\n\003BUY\020\000\022\010\n\004SELL\020\0012\251" +
      "\001\n\014StockService\022\"\n\014getAllStocks\022\006.Empty\032" +
      "\006.Stock\"\0000\001\022\035\n\010setOrder\022\006.Order\032\007.Status" +
      "\"\000\022(\n\014filterOrders\022\014.FilterQuery\032\006.Order" +
      "\"\0000\001\022,\n\007getLogs\022\013.TradesDate\032\020.TradeLogM" +
      "essage\"\0000\001B\010\n\004gRpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FilterQuery_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FilterQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FilterQuery_descriptor,
        new java.lang.String[] { "Symbol", "Quantity", "Action", });
    internal_static_TradesDate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TradesDate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradesDate_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_TradeLogMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TradeLogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeLogMessage_descriptor,
        new java.lang.String[] { "Log", });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "Action", "Id", });
    internal_static_Status_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_Stock_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Stock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Stock_descriptor,
        new java.lang.String[] { "Symbol", "Name", "Price", "PercentageChange", "Date", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
