// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StockService.proto

package gRpc;

public interface TradeLogMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TradeLogMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string log = 1;</code>
   * @return The log.
   */
  java.lang.String getLog();
  /**
   * <code>string log = 1;</code>
   * @return The bytes for log.
   */
  com.google.protobuf.ByteString
      getLogBytes();
}
